device/device/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from htgl import views
from django.views.generic.base import RedirectView
from django.views.static import serve

urlpatterns = [
   # path('admin/', views.index),
   path("favicon.ico",RedirectView.as_view(url='static/favicon.ico')),
   url(r'^upload/(?P<path>.*)$', serve, {'document_root': 'upload'}),
   url(r'^admin/', admin.site.urls),
   path('login/', views.login_user),
   path('logout/', views.logout),
   path('borrow/audit/', views.borrowAudit),
   path('device/disagree/<int:id>', views.borrowAudit2),
   path('borrow/add/', views.borrowAdd),
   path('borrow/', views.borrowList),
   path('borrow/<int:id>', views.borrowDetail),
   path('borrow/delete/<int:id>', views.borrowDelete),
   path('borrow/edit/<int:id>', views.borrowEdit),
   path('borrow/return/<int:id>', views.borrowReturn),
   path('device/<int:id>', views.deviceDetail),
   path('device/delete/<int:id>', views.deviceDelete),
   path('device/edit/<int:id>', views.deviceEdit),
   path('device/add/', views.deviceAdd),
   path('device/', views.deviceList),
   path('diary/<int:id>', views.diaryDetail),
   path('diary/delete/<int:id>', views.diaryDelete),
   path('diary/edit/<int:id>', views.diaryEdit),
   path('diary/add/', views.diaryAdd),
   path('diary/', views.diaryList),
   path('member/get/', views.memberList),
   path('project/',views.projectList),
   # path('cartridge/', views.cartridgeList),
   # path('cartridge/detail/<int:id>', views.cartridgeDetail),
   # path('cartridge/update/<int:id>', views.cartridgeUpdate),
   # path('cartridge/delete/<int:id>', views.cartridgeDelete),
   # path('cartridge/add/', views.cartridgeAdd)
   # url(r'^device/', views.deviceList),
   path('', views.index),
   path('index/', views.index),
   path('api/people/', views.people_list),
   path('api/people/update/', views.people_update),
   path('api/people/search/', views.people_search),
   path('api/advice/', views.advice_list),
   path('api/advice/add/', views.advice_add),
   path('api/advice/addpic/', views.advice_addpic),
   path('api/advice/edit/', views.advice_edit),
   path('api/advice/detail/', views.advice_detail),
   path('api/advice/delete/', views.advice_delete),
   path('api/Cartridge/update/', views.Cartridge_update),
   path('api/borrow/audit/', views.borrow_audit),
   path('api/borrow/detail/', views.borrow_detail),
   path('api/borrow/add/', views.borrow_add),
   path('api/borrow/list/', views.borrow_list),
   path('api/borrow/auditlist/', views.borrow_auditlist),
   path('api/member/detail/', views.member_detail),
   path('api/dd/getuser/', views.dd_getuser)
   #path('api/advice/delete', views.advice_delete),
]

device/htgl/models.py
from django.db import models, reset_queries


# Create your models here.


class Cartridge(models.Model):
   model = models.CharField(max_length=20, blank=False, null=False, verbose_name='型号')
   color = models.CharField(max_length=5, blank=True, null=True, verbose_name='颜色')
   code = models.CharField(max_length=4, blank=True, null=True)
   number = models.IntegerField(blank=True, null=True, verbose_name='数量')
   brand = models.CharField(max_length=20, blank=True, null=True, verbose_name='品牌')

   class Meta:
      managed = True
      db_table = 'cartridge'
      verbose_name = '耗材'
      verbose_name_plural = verbose_name

   def __str__(self):
      data = self.model + '(' + self.color + ')'
      return data


class sys(models.Model):
   codename = models.CharField(db_column='codeName', max_length=20, blank=True, null=True, verbose_name='名称')
   sort = models.IntegerField(blank=True, null=True, verbose_name='排序')
   type = models.IntegerField(blank=True, null=True, verbose_name='代码类别',
                              choices=((1, '设备类别'), (2, '设备状态'), (3, '设备审批'), (4, '借用状态'),
                                       (5, '负责人'), (6, '进度'), (7, '模块')))

   class Meta:
      managed = True
      db_table = 'sys'
      verbose_name = '代码'
      verbose_name_plural = verbose_name

   def __str__(self):
      return self.codename


class department(models.Model):
   depname = models.CharField(db_column='depName', max_length=20, blank=True, null=True, verbose_name='名称')
   dingid = models.CharField(db_column='dingID', max_length=20, blank=True, null=True, unique=True, verbose_name='dingID')
   sort = models.IntegerField(blank=True, null=True, verbose_name='排序')

   class Meta:
      managed = True
      db_table = 'department'
      verbose_name = '部门'
      verbose_name_plural = verbose_name

   def __str__(self):
      return self.depname


class member(models.Model):
   dingid = models.CharField(db_column='dingID', max_length=20, blank=True, null=True, unique=True, verbose_name='钉钉编号')
   name = models.CharField(db_column='memberName', max_length=10, blank=False, null=False, verbose_name='姓名')
   sort = models.IntegerField(blank=True, null=True, verbose_name='排序')
   depid = models.ForeignKey(department, db_column='depID', to_field='id', null=True, blank=True, verbose_name='所属处室', on_delete=models.PROTECT)

   class Meta:
      managed = True
      db_table = 'member'
      verbose_name = '人员'
      verbose_name_plural = verbose_name

   def __str__(self):
      return self.name


class Printer(models.Model):
   model = models.CharField(max_length=50, blank=True, null=True, verbose_name='型号')
   brand = models.CharField(max_length=10, blank=True, null=True, verbose_name='品牌')
   pic = models.CharField(max_length=100, blank=True, null=True)
   cartridges = models.CharField(max_length=50, blank=True, null=True, verbose_name='使用的硒鼓')

   class Meta:
      managed = True
      db_table = 'printer'
      verbose_name = '打印机型号'
      verbose_name_plural = '型号'


class PrinterType(models.Model):
   model = models.CharField(max_length=50, blank=True, null=True, verbose_name='型号')
   brand = models.CharField(max_length=10, blank=True, null=True, verbose_name='品牌')
   pic = models.CharField(max_length=100, blank=True, null=True)
   cartridges = models.ManyToManyField('cartridge', verbose_name='使用的硒鼓')

   class Meta:
      managed = True
      db_table = 'printertype'
      verbose_name = '打印机型号'
      verbose_name_plural = '型号'


class Device(models.Model):
   model = models.CharField(max_length=50, blank=False, null=False, verbose_name='品牌和型号')
   brand = models.CharField(max_length=10, blank=True, null=True, verbose_name='品牌', editable=False)
   pic = models.CharField(max_length=100, blank=True, null=True, verbose_name='图片', editable=False)
   sn = models.CharField(max_length=50, blank=True, null=True, verbose_name='序列号')
   type = models.ForeignKey(sys, db_column='type', to_field='id', null=True, verbose_name='类别', limit_choices_to={'type': '1'},
                            on_delete=models.PROTECT)
   depid = models.ForeignKey(department, db_column='depID', to_field='id', null=True, blank=True, verbose_name='责任处室', on_delete=models.PROTECT)
   memid = models.ForeignKey(member, db_column='memID', to_field='id', null=True, blank=True, verbose_name='责任人', on_delete=models.PROTECT)
   room = models.CharField(max_length=20, blank=True, null=True, verbose_name='房间号')
   buytime = models.DateField(db_column='buyTime', blank=True, null=True, verbose_name='购置时间')
   memo = models.CharField(max_length=200, blank=True, null=True, verbose_name='备注')
   status = models.ForeignKey(sys, db_column='status', blank=True, null=True, related_name='zt', to_field='id', limit_choices_to={'type': '2'},
                              verbose_name='状态', on_delete=models.PROTECT)
   recordtime = models.DateTimeField(blank=True, null=True, auto_now_add=True)
   updatetime = models.DateTimeField(blank=True, null=True, auto_now=True)

   class Meta:
      managed = True
      db_table = 'device'
      verbose_name = '设备管理'
      verbose_name_plural = '设备'

   def __str__(self):
      return self.model


class RecordBorrow(models.Model):
   userid = models.ForeignKey(member, to_field='dingid', db_column='userid', null=True, on_delete=models.PROTECT, verbose_name='申请人')
   depid = models.ForeignKey(department, db_column='depID', to_field='dingid', null=True, verbose_name='申请处室', on_delete=models.PROTECT)
   devices = models.ManyToManyField(Device, verbose_name='借用设备')
   etime = models.DateField(blank=True, null=True, verbose_name='归还时间')
   stime = models.DateField(blank=True, null=True, verbose_name='借用时间')
   reason = models.TextField(max_length=500, blank=True, null=True, verbose_name='借用原因及要求')
   memo = models.CharField(max_length=200, blank=True, null=True, verbose_name='备注')
   status = models.ForeignKey(sys, db_column='status', blank=True, null=True, related_name='jyzt', to_field='id', limit_choices_to={'type': '3'},
                              verbose_name='状态', default=15, on_delete=models.PROTECT)
   recordtime = models.DateTimeField(auto_now_add=True, verbose_name='生成时间', null=True, editable=False)
   updatetime = models.DateTimeField(auto_now=True, verbose_name='更新时间', null=True, editable=False)

   class Meta:
      managed = True
      db_table = 'record_borrow'
      verbose_name = '设备借用'
      verbose_name_plural = verbose_name


# 硒鼓申领
class RecordApply(models.Model):
   userid = models.CharField(max_length=20, blank=True, null=True)
   username = models.CharField(max_length=20, blank=True, null=True, verbose_name='申领人')
   deptid = models.CharField(db_column='deptID', max_length=20, blank=True,null=True)
   department = models.CharField(max_length=20, blank=True, null=True, verbose_name='申领部门')
   recordtime = models.DateTimeField(blank=True, null=True, verbose_name='申领时间')
   amount = models.IntegerField(blank=True, null=True, verbose_name='数量')
   crid = models.ForeignKey(Cartridge, db_column='crID', to_field='id', null=True, on_delete=models.PROTECT,verbose_name='申领耗材')
   ctime = models.DateTimeField(blank=True, null=True, verbose_name='确认时间')
   memo = models.CharField(max_length=200, blank=True, null=True, verbose_name='备注')

   class Meta:
      managed = True
      db_table = 'record_apply'
      verbose_name = '耗材申领记录'
      verbose_name_plural = verbose_name


class RecordDevice(models.Model):
   did = models.ForeignKey(Device, db_column='dID', to_field='id', null=True, on_delete=models.PROTECT, verbose_name='设备id')
   borrowid = models.ForeignKey(RecordBorrow, db_column='borrowID', to_field='id', on_delete=models.PROTECT, null=True, verbose_name='借用id')
   returntime = models.DateField(blank=True, null=True, verbose_name='归还时间')
   status = models.ForeignKey(sys, db_column='status', blank=True, null=True, related_name='ghzt', to_field='id', limit_choices_to={'type': '4'},
                              verbose_name='状态', on_delete=models.PROTECT)
   recordtime = models.DateTimeField(null=True, auto_now_add=True)
   updatetime = models.DateTimeField(null=True, auto_now=True)

   class Meta:
      managed = True
      db_table = 'record_device'
      verbose_name = '借用记录'
      verbose_name_plural = verbose_name
      unique_together = (('did', 'borrowid'),)


class ecsstatus(models.Model):
   name = models.CharField(max_length=15, blank=False, null=False, verbose_name='名称')

   class Meta:
      managed = True
      db_table = 'ecsstatus'
      verbose_name = '状态'
      verbose_name_plural = verbose_name
      sorted('id')

   def __str__(self):
      return self.name


class ecs(models.Model):
   ip = models.CharField(max_length=15, blank=False, null=False, verbose_name='内网IP', unique=True)
   internetip = models.CharField(max_length=15, blank=True, null=True, verbose_name='互联网ip')
   os = models.CharField(max_length=50, blank=False, null=False, verbose_name='操作系统', default='Windows Server 2008 R2')
   sn = models.CharField(max_length=50, blank=False, null=False, unique=True, verbose_name='实例id')
   status = models.ForeignKey(ecsstatus, db_column='status', to_field='id', null=False, verbose_name='状态', on_delete=models.PROTECT, default=1)
   net = models.CharField(max_length=4, null=False, blank=False, choices=(('VPN1', 'VPN1'), ('VPN2', 'VPN2'), ('VPN3', 'VPN3')), default='VPN1')
   group = models.IntegerField(null=False, blank=False, choices=((1, '转塘集群'), (2, '青山湖集群')), default=1)
   cpu = models.CharField(max_length=20, blank=True, null=True, verbose_name='CPU', default='8核')
   ram = models.CharField(max_length=20, blank=True, null=True, verbose_name='内存', default='16G')
   disk = models.CharField(max_length=20, blank=True, null=True, verbose_name='硬盘', default='500G')
   memo = models.CharField(max_length=200, blank=True, null=True, verbose_name='备注')
   recordtime = models.DateTimeField(blank=True, null=True, auto_now_add=True)
   updatetime = models.DateTimeField(blank=True, null=True, auto_now=True)

device/templates/cartridge/add.html
<!DOCTYPE html>

<html lang="zh-Hans">
<head>
   <title>修改 设备管理 | 设备管理</title>
   <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
   <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
   <script type="text/javascript" src="/admin/jsi18n/"></script>
   <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
   <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
   <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
   <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
   <script type="text/javascript" src="/static/admin/js/core.js"></script>
   <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
   <script type="text/javascript" src="/static/admin/js/actions.js"></script>
   <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
   <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
   <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
   <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
   <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
   <meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>
   <div id="content" class="colM">
      <h1><a href="javascript:history.back(-1)"><返回</a> 硒鼓详情 |  编辑</h1>
      <div id="content-main">
         <form action="" method="post" id="cartridge_form" novalidate>
             {%csrf_token%}
            <div>
               <fieldset class="module aligned ">
                  <div class="form-row field-model">
                     <div>
                        <label class="required" for="id_model">型号:</label>
                        <input type="text" name="model" class="vTextField" maxlength="20" required id="id_model" value="{{list.model}}">
                     </div>
                  </div>
                  <div class="form-row field-brand">
                     <div>
                        <label for="id_brand">品牌:</label>
                        <input type="text" name="brand" value="{{list.brand}}" class="vTextField" maxlength="10">
                     </div>
                  </div>
                  <div class="form-row field-pic">
                     <div>
                        <label for="id_pic">颜色:</label>
                        <input type="text" name="color" value="{{list.color}}" class="vTextField" maxlength="5">
                     </div>
                  </div>
                  <div class="form-row field-sn">
                     <div>
                        <label for="id_sn">库存:</label>
                        <input type="number" name="number" value="{{list.number}}" class="vIntegerField">
                     </div>
                  </div>
               </fieldset>
               <div class="submit-row">
                  <input type="submit" value="保存" class="default" name="_save">
                  <p class="deletelink-box">
                     <a href="/cartridge/delete/{{list.id}}" class="deletelink" onClick="return confirm('确定删除?');">删除</a>
                  </p>
               </div>
            </div>
         </form>
      </div>
   </div>
</body>
</html>

device/templates/cartridge/detail.html
<!DOCTYPE html>

<html lang="zh-Hans">
<head>
    <title>修改 设备管理 | 设备管理</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>
<div id="content" class="colM">
    <h1><a href="javascript:history.back(-1)">
        <返回
    </a> 设备详情 | 编辑
    </h1>
    <div id="content-main">
        <form action="/cartridge/update/{{list.id}}" method="post" id="cartridge_form" novalidate>
            {%csrf_token%}
            <div>
                <fieldset class="module aligned ">
                    <div class="form-row field-model">
                        <div>
                            <label for="id_model">型号:</label>
                            <input type="text" name="model" value="{{list.model}}" class="vTextField" maxlength="50"
                                   id="id_model">
                        </div>
                    </div>
                    <div class="form-row field-brand">
                        <div>
                            <label for="id_brand">品牌:</label>
                            <input type="text" name="brand" value="{{list.brand}}" class="vTextField" maxlength="10"
                                   id="id_brand">
                        </div>
                    </div>
                    <div class="form-row field-sn">
                        <div>
                            <label>颜色:</label>
                            <input type="text" name="color" value="{{list.color}}" class="vTextField" maxlength="50">
                        </div>
                    </div>
                    <div class="form-row field-sn">
                        <div>
                            <label>库存:</label>
                            <input type="text" name="number" value="{{list.number}}" class="vTextField" maxlength="50">
                        </div>
                    </div>
                </fieldset>
                <div class="submit-row">
                    <input type="submit" value="保存" class="default" name="_save">
                    <p class="deletelink-box">
                        <a href="/cartridge/delete/{{list.id}}" class="deletelink" onClick="return confirm('确定删除?');">删除</a>
                    </p>
                </div>
                <script type="text/javascript" id="django-admin-form-add-constants" src="/static/admin/js/change_form.js">
                </script>
                <script type="text/javascript" id="django-admin-prepopulated-fields-constants"
                        src="/static/admin/js/prepopulate_init.js" data-prepopulated-fields="[]">
                </script>
            </div>
        </form>
    </div>
</div>
</body>
</html>

device/templates/cartridge/list.html
<!DOCTYPE html>

<html lang="zh-Hans">
<head>
   <title>硒鼓管理 | 设备管理</title>
   <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
   <link rel="stylesheet" type="text/css" href="/static/admin/css/changelists.css">
   <script type="text/javascript" src="/admin/jsi18n/"></script>
   <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
   <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
   <script type="text/javascript" src="/static/admin/js/core.js"></script>
   <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
   <script type="text/javascript" src="/static/admin/js/actions.js"></script>
   <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
   <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
   <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
   <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
   <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
   <meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>
<!-- Container -->
<div id="content" class="flex">
   <div id="content-main">

      <div class="module filtered" id="changelist">
         <div id="toolbar" style="position: relative;height: 50px;padding: 0;margin: 0">
                <div class="object-tools" style="position: absolute;left: 10px;margin: 0;line-height: 30px;top:7px;padding: 0">
                    <a href="/cartridge/add/" class="addlink">增加硒鼓</a>
                </div>
               <div style="position: absolute;left: 200px;top:10px;line-height: 30px;"><!-- DIV needed for valid HTML -->
                  <label for="searchbar"><img src="/static/admin/img/search.svg" alt="Search"></label>
                  <input type="text" size="40" name="q" value="" id="searchbar" autofocus>
                  <input type="submit" value="搜索" style="height: 30px;line-height: 30px;margin: 0;padding: 0;width: 100px;">
               </div>
         </div>
         <form id="changelist-form" method="post" novalidate>
            <div class="results">
               <table id="result_list">
                  <thead>
                  <tr>
                     <th scope="col" class="sortable column-id">
                        <div class="text"><a href="?o=1">ID</a></div>
                        <div class="clear"></div>
                     </th>
                     <th scope="col" class="sortable column-model">
                        <div class="text"><a href="?o=2">型号</a></div>
                        <div class="clear"></div>
                     </th>
                     <th scope="col" class="sortable column-brand">
                        <div class="text"><a href="?o=3">品牌</a></div>
                        <div class="clear"></div>
                     </th>
                     <th scope="col" class="sortable column-pic">
                        <div class="text"><a href="?o=4">颜色</a></div>
                        <div class="clear"></div>
                     </th>
                     <th scope="col" class="sortable column-pic">
                        <div class="text"><a href="?o=4">库存</a></div>
                        <div class="clear"></div>
                     </th>
                  </tr>
                  </thead>
                  {%for d in list%}
                  <tr class="row1">
                     <th class="field-id"><a href="/cartridge/detail/{{d.id}}">{{d.id}}</a></th>
                     <td class="field-model">{{d.model}}</td>
                     <td class="field-brand">{{d.brand}}</td>
                     <td class="field-pic">{{d.color}}</td>
                     <td class="field-pic">{{d.number}}</td>
                  </tr>
                  {% endfor %}
                  </tbody>
               </table>
            </div>
            <p class="paginator">
            </p>
         </form>
      </div>
   </div>
</div>
</div>
<!-- END Container -->

</body>
</html>